### ISSUE TITLE
I meant that DeepDiff could, in that rare circumstance, return nothing (no diff) without `restart` ever taking place.

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/mimir-k8s-operator#8]
something to investigate:

 
       I meant that DeepDiff could, in that rare circumstance, return nothing (no diff) without `restart` ever taking place.
Which makes me wonder if charm code should always `replan()`, just in case.

_Originally posted by @sed-i in https://github.com/canonical/mimir-k8s-operator/pull/7#discussion_r1036170276_

**Comment by rbarry82** [comment]
No longer using `DeepDiff`
